# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        font = QtGui.QFont()
        font.setPointSize(30)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 400, 76))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(180, 180, 180);\n"
"color: #000000;\n"
"padding: 1px")
        self.label.setObjectName("label")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(0, 394, 200, 106))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("QPushButton {\n"
"    background-color: rgb(210, 210, 210);\n"
"    border: solid\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(193, 193, 193);\n"
"}")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 288, 100, 106))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("QPushButton {\n"
"    background-color: rgb(210, 210, 210);\n"
"    border: solid\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(193, 193, 193);\n"
"}")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 288, 100, 106))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(210, 210, 210);\n"
"    border: solid\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(193, 193, 193);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 288, 100, 106))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(210, 210, 210);\n"
"    border: solid\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(193, 193, 193);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(100, 182, 100, 106))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(210, 210, 210);\n"
"    border: solid\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(193, 193, 193);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 182, 100, 106))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(210, 210, 210);\n"
"    border: solid\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(193, 193, 193);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(200, 182, 100, 106))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: rgb(210, 210, 210);\n"
"    border: solid\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(193, 193, 193);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(200, 76, 100, 106))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: rgb(210, 210, 210);\n"
"    border: solid\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(193, 193, 193);\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(100, 76, 100, 106))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: rgb(210, 210, 210);\n"
"    border: solid\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(193, 193, 193);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 76, 100, 106))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: rgb(210, 210, 210);\n"
"    border: solid\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(193, 193, 193);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(300, 182, 100, 106))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background-color: rgb(210, 210, 210);\n"
"    border: solid\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(193, 193, 193);\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(300, 288, 100, 106))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    background-color: rgb(210, 210, 210);\n"
"    border: solid\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(193, 193, 193);\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(300, 76, 100, 106))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    background-color: rgb(210, 210, 210);\n"
"    border: solid\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(193, 193, 193);\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(300, 394, 100, 106))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"    background-color: rgb(210, 210, 210);\n"
"    border: solid\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(193, 193, 193);\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(200, 394, 100, 106))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"    background-color: rgb(210, 210, 210);\n"
"    border: solid\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(193, 193, 193);\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.label.setText(_translate("MainWindow", "0"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_10.setText(_translate("MainWindow", "-"))
        self.pushButton_11.setText(_translate("MainWindow", "*"))
        self.pushButton_12.setText(_translate("MainWindow", "+"))
        self.pushButton_13.setText(_translate("MainWindow", "/"))
        self.pushButton_14.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
